const mongoose = require('mongoose');

const ContributionsSchema = new mongoose.Schema(
  {
    contributions_id: {
        type: mongoose.Schema.Types.ObjectId, // ObjectId reference
        ref: 'Employee', // Refers to the Employee model
        required: true, // Ensure the field is mandatory
    },
    // Primary Key (id is automatically generated by MongoDB)
    sssNumber: {
      type: String,
      required: true, // Ensure the field is mandatory
      trim: true, // Remove extra spaces
    },
    philHealthNumber: {
      type: String,
      required: true, // Ensure the field is mandatory
      trim: true,
    },
    pagibigNumber: {
      type: String,
      required: true, // Ensure the field is mandatory
      trim: true,
    },
    tinNumber: {
      type: String,
      required: true, // Ensure the field is mandatory
      trim: true,
    },
    
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields automatically
  }
);

module.exports = mongoose.model('Contributions', ContributionsSchema);
